<link rel="stylesheet" href="/layui/src/layuiadmin/layui/css/layui.css" media="all">
<link rel="stylesheet" href="/layui/dist/layuiadmin/style/admin.css" media="all">
<link rel="stylesheet" href="/layui/dist/layuiadmin/style/template.css">
<!-- 
<link rel="stylesheet" href="/layui/dist/admin/css/font.css">
<link rel="stylesheet" href="/layui/dist/admin/css/xadmin.css">
 -->
<script type="text/javascript" src="/js/jquery/jquery-1.8.2.min.js"></script>
<script type="text/javascript" src="/layui/dist/layuiadmin/layui/layui.js"></script>  
<script type="text/javascript" src="/layui/dist/admin/js/xadmin.js"></script>
<script type="text/javascript">
function RndNum(n) {
    var rnd = "";
    for (var i = 0; i < n; i++)
        rnd += Math.floor(Math.random() * 10);
    return rnd;
}
function logoff(url){
	window.parent.location.href = url;
}
function refresh(){
    window.location.reload();
}
</script>

<style>
.layui-form-label{
	text-align:left;
	width:auto;
}
/* 偶数行背景色 */
.layui-table[lay-even] tr:nth-child(even) {
    /* background-color: #aaffaa; */
    background-color: #eeffee;
}
/* 鼠标指向表格时,奇数行背景颜色 */
.layui-table tbody tr:hover,.layui-table-hover {
    background-color: #eeffee;
}
/* 表格头部工具栏背景色 */
.layui-table-tool {
    background-color: #eeffee;
}
/* 表格头部背景色 */
th {
    background-color: #5FB878; /* MediumSeaGreen */
    color: #fff;
    font-weight: bold
}
</style>