<?php echo $this->render('manage/header.phtml');?>
<head>
<meta charset="utf-8">
<meta name="renderer" content="webkit">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
<?php echo $this->render("manage/layui.phtml");?>
</head>
<body>
<div class="layui-fluid">
	<div class="layui-card">
		<div class="layui-card-body">
			<?php echo $this->render('manage/title.phtml');?>
			<!-- 
			<div class="layui-collapse" lay-filter="test" style="margin-bottom: 10px;">
				<div class="layui-colla-item">
				</div>
			</div>
			 -->
		        <div style="padding-bottom: 10px;">
					<button class="layui-btn layuiadmin-btn-admin" data-type="add" id="add">添加</button>
				</div>
			   <table id="tableList" class="layui-table" lay-filter="tableList"></table>
				<script type="text/html" id="oper-col">
					<a class="layui-btn layui-btn-normal layui-btn-xs" lay-event="edit">修改</a>
					<a class="layui-btn layui-btn-danger layui-btn-xs" lay-event="del">删除</a>
				</script>
		</div>
	</div>
</div>
<script type="text/javascript">
layui.config({
	base: '/layui/dist/layuiadmin/lib/' //静态资源所在路径
}).extend({
    treetable: 'treetable-lay/treetable'
}).use(['layer', 'table', 'treetable', 'form', 'jquery'], function () {
    var $ = layui.jquery;
    var table = layui.table;
    var layer = layui.layer;
    var treetable = layui.treetable;

	// 渲染表格
    var renderTable = function () {
        layer.load(2);
        treetable.render({
    	    size: 'sm',
    	    even: true,
            treeColIndex: 1,
            treeSpid: 0,
            treeIdName: 'id',
            treePidName: 'parentId',
            treeDefaultClose: false,
            treeLinkage: false,
            elem: '#tableList',
            url: '/manage/menu-process?act=menuList',
            page: false,
            cols: [[
                {type: 'numbers'},
                {field: 'title', title: '功能名称'},
                {field: 'url', title: '功能地址'},
                {field: 'parentTitle', title: '所属分组'},
                {templet: '#oper-col', title: '操作', align:'center'}
            ]],
            done: function () {
                layer.closeAll('loading');
            }
        });
    };
    
    renderTable();

    //监听工具条
    table.on('tool(tableList)', function (obj) {
        var data = obj.data;
        var layEvent = obj.event;

        if (layEvent === 'del') {
            layer.msg('删除' + data.id);
        } else if (layEvent === 'edit') {
			x_admin_show('修改','/manage/menu-edit?menuId='+data.id);
        }
    });
	$('#add').click(function () {
		x_admin_show('添加','/manage/menu-edit?menuId=0');
	});
});
</script>
<?php echo $this->render('manage/footer.phtml'); ?>