<?php echo $this->render('manage/header.phtml');?>
<head>
<meta charset="utf-8">
<meta name="renderer" content="webkit">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
<?php echo $this->render("manage/layui.phtml");?>
</head>
<body>
<div class="layui-fluid">
	<div class="layui-card">
		<div class="layui-card-body">
			<?php echo $this->render('manage/title.phtml');?>
			<!-- 
			<div class="layui-collapse" lay-filter="test" style="margin-bottom: 10px;">
				<div class="layui-colla-item">
				</div>
			</div>
			 -->
		        <div style="padding-bottom: 10px;">
					<button class="layui-btn layuiadmin-btn-admin" data-type="add" id="add">添加</button>
				</div>
				<table id="tableList" lay-filter='tableList'></table>
				<script type='text/html' id="operation">
     				<a class="layui-btn layui-btn-xs layui-bg-cyan" lay-event='organizePurviewList'>用户组权限编辑</a>
     				<a class="layui-btn layui-btn-xs layui-btn-normal" lay-event='edit'>修改</a>
					<!--<a class="layui-btn layui-btn-xs layui-btn-normal" lay-event='detail'>明细</a>-->
					<a class="layui-btn layui-btn-danger layui-btn-xs" lay-event="del">删除</a>
				</script>
		</div>
	</div>
</div>
<script type="text/javascript">
layui.use(['form', 'jquery', 'table', 'layer'], function () {
	var form = layui.form,$ = layui.jquery,layer = layui.layer,table = layui.table;
	var loading=layer.msg('数据加载中...',{icon:16})
	table.render({
		elem: '#tableList',
	    even: true,
	    size: 'sm',
		page: true,
		limit: 15,
		limits: [15],
		url: '/manage/organize-process?act=pageList',
		cols: [[
			{type: 'numbers'},
// 			{field: 'id', title: 'ID',align:'left'},
			{field: 'title', title: '标题',align:'left'},
			{field:　'operation', title: '操作', toolbar: '#operation',align:'center'}
		]],
		id: 'tableList',
		done:function(){
			layer.close(loading);
		}
	});
	table.on('tool(tableList)', function (obj) {
		var data = obj.data,layEvent = obj.event;
		var id = data.id;
		if(layEvent === 'edit'){
			x_admin_show('修改','/manage/organize-edit?organizeId='+data.id);
		}else if(layEvent === 'del') {
			layer.confirm('确定删除吗？', function(index){
				$.ajax({
					url: "/manage/organize-process",
					data: {
						act:"removeOrganize",
						organizeId:data.id
					},
					type: 'POST',
					dataType: "json",
					success: function(data){
						if (data.code == 0){
							layer.msg(data.msg, {icon: 1,time:3000},function () {
								var index = parent.layer.getFrameIndex(window.name);
	//	 						parent.layer.close(index);
							});
		                    table.reload('tableList');
						} else{
							layer.msg(data.msg, {icon: 5,time: 3000});
						}
	//	 				table.reload("tableList");
					}
				});
			});
        }else if(layEvent === 'organizePurviewList') {
			x_admin_show('用户组权限编辑','/manage/organize-purview-list?organizeId='+data.id);
        }
	});
	$('#add').click(function () {
		x_admin_show('添加','/manage/organize-edit?organizeId=0');
	});
});
</script>
<?php echo $this->render('manage/footer.phtml'); ?>