<?php echo $this->render('manage/header.phtml');?>
<head>
<meta charset="utf-8">
<meta name="renderer" content="webkit">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
<?php echo $this->render("manage/layui.phtml");?>
</head>
<body>
<div class="layui-fluid">
	<div class="layui-card">
		<div class="layui-card-body">
			<!-- 
			<div class="layui-collapse" lay-filter="test" style="margin-bottom: 10px;">
				<div class="layui-colla-item">
				</div>
			</div>
			 -->
		        <div style="padding-bottom: 10px; float:right;">
					<button class="layui-btn layuiadmin-btn-admin" data-type="add" id="update">更新</button>
				</div>
			   <table id="tableList" class="layui-table" lay-filter="tableList"></table>
				<script type="text/html" id="oper-col">
					{{#  if(d.parentId > 0){ }}
					<input type="checkbox" name="relation" value="{{d.id}}" title="访问权限" {{ d.relation == true ? 'checked' : '' }}>
						{{# if(d.relation){ }}
						<input type="checkbox" name="readonly" value="{{d.id}}" title="读写权限" {{ d.readonly == true ? 'checked' : '' }}>
						{{# } }}
					{{# } }}
				</script>
		</div>
	</div>
</div>
<script type="text/javascript">
layui.config({
	base: '/layui/dist/layuiadmin/lib/' //静态资源所在路径
}).extend({
    treetable: 'treetable-lay/treetable'
}).use(['layer', 'table', 'treetable', 'form', 'jquery'], function () {
    var $ = layui.jquery;
    var table = layui.table;
    var layer = layui.layer;
    var treetable = layui.treetable;

	// 渲染表格
    var renderTable = function () {
        layer.load(2);
        treetable.render({
            treeColIndex: 1,
            treeSpid: 0,
            treeIdName: 'id',
            treePidName: 'parentId',
            treeDefaultClose: false,
            treeLinkage: false,
            elem: '#tableList',
            url: '/manage/user-process?act=userRelationList&userId=<?php echo $this->userId;?>',
            page: false,
            cols: [[
                {type: 'numbers'},
                {field: 'title', title: '功能名称'},
                {field: 'url', title: '功能地址'},
                {field: 'parentTitle', title: '所属分组'},
                {field: 'relation', title:'操作', align:'left', templet: '#oper-col', unresize: true},
//                 {templet: '#oper-col', title: '操作'}
            ]],
            done: function () {
                layer.closeAll('loading');
            }
        });
    };

    renderTable();

	$('#update').click(function () {
		var relationArr = new Array();
		var readonlyArr = new Array();
		$("input[name='relation']:checked").each(function(){
			relationArr.push($(this).val());
		});
		$("input[name='readonly']:checked").each(function(){
			readonlyArr.push($(this).val());
		});
		console.log(relationArr);
		console.log(readonlyArr);
// 		return false;


		$.ajax({
			url: "/manage/user-process",
			data: {
				act:"userRelationEdit",
				userId:<?php echo $this->userId;?>,
				relation:relationArr,
				readonly:readonlyArr
			},
			type: 'POST',
			dataType: "json",
			success: function(data){
				if (data.code == 0){
					layer.msg(data.msg, {icon: 1,time:3000},function () {
						var index = parent.layer.getFrameIndex(window.name);
//	 						parent.layer.close(index);
					});
                    table.reload('tableList');
				} else{
					layer.msg(data.msg, {icon: 5,time: 3000});
				}
//	 				table.reload("tableList");
			}
		});
    	renderTable();
	});
});
</script>
<?php echo $this->render('manage/footer.phtml'); ?>