<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title><?php echo SYSTEM_TITLE;?></title>
<meta name="renderer" content="webkit">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
<?php echo $this->render("manage/layui.phtml");?>
<link rel="stylesheet" href="/layui/dist/layuiadmin/css/login.css" media="all">
<script src="/layui/dist/layuiadmin/lib/jq-module/jquery.particleground.min.js"></script>
<script type="text/javascript">
function RndNum(n) {
    var rnd = "";
    for (var i = 0; i < n; i++)
        rnd += Math.floor(Math.random() * 10);
    return rnd;
}
</script>
</head>
<body>
    <div class="layui-container">
        <div class="admin-login-background">
            <div class="layui-form login-form">
                <form class="layui-form" id="form" action="/signin/login.check.process">
                	<input type="hidden" name="act" value="login" />
                    <div class="layui-form-item logo-title">
                        <h1><?php echo SYSTEM_TITLE;?></h1>
                    </div>
                    <div class="layui-form-item">
                        <label class="layui-icon layui-icon-username" for="username"></label>
                        <input type="text" name="username" lay-verify="required|account" placeholder="用户名或者邮箱" autocomplete="off" class="layui-input" value="admin">
                    </div>
                    <div class="layui-form-item">
                        <label class="layui-icon layui-icon-password" for="password"></label>
                        <input type="password" name="password" lay-verify="required|password" placeholder="密码" autocomplete="off" class="layui-input" value="admin123!@#">
                    </div>
                    <div class="layui-form-item">
                        <label class="layui-icon layui-icon-vercode" for="captcha"></label>
                        <input type="text" name="vcode" lay-verify="required|captcha" placeholder="图形验证码" autocomplete="off" class="layui-input verification captcha">
                        <div class="captcha-img">
                        	<img id="validate" style="width: 106px; height: 36px; cursor: pointer;" src="/func/validate/validate.php" alt="点击刷新" />
                        </div>
                    </div>
                    <div class="layui-form-item" style="height: 28px;">
                        <input type="checkbox" name="rememberMe" value="true" lay-skin="primary" title="记住密码">
                    </div>
                    <div class="layui-form-item">
                        <button class="layui-btn layui-btn-fluid" lay-submit="" lay-filter="login">登 入</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <script>
    // 粒子线条背景
    $(function () {
        $('.layui-container').particleground({
            dotColor: '#5cbdaa',
            lineColor: '#5cbdaa'
        });
    	$("#validate").bind("click", function(){
    		$(this).attr("src","/func/validate/validate.php?flag=" + RndNum(8));
    	});
		if(event.keyCode ==13){
			$("#signin").trigger("click");
		}
    });
    layui.use(['form'], function () {
        var form = layui.form,
            layer = layui.layer,
            $ = layui.$;
        //登录过期的时候，跳出ifram框架
        if (top.location != self.location) top.location = self.location;

        //进行登录操作
        form.on('submit(login)', function (data) {
        	$.ajax({
    			url : $("#form").attr("action"),
    			type : 'POST',
    			dataType: "json",
//     			data: new FormData($('#form')[0]),
    			data : data.field,
    			success : function(data, response, status) {
//     				var jsonData = $.parseJSON(data);
    				var jsonData = data;
    				if (jsonData.code > 0) {
    					layer.msg(jsonData.msg, { icon: 1 }, function(){
    						location.href = '/manage/index'; //后台主页
    			        });
    				} else {
    					layer.msg(data.msg, {icon: 5});
    				}
    			},
    			error: function() {
                    layer.msg('网络错误....', { icon: 5, shift: 6 });
                }
    		});
    		return false;
        });
    });
    </script>
</body>
</html>