DROP PROCEDURE `V_TRANSACTION_ACCOUNT_TOTAL`//
CREATE DEFINER=`root`@`localhost` PROCEDURE `V_TRANSACTION_ACCOUNT_TOTAL`()
BEGIN
	DECLARE YEAR_SUCCESS_MONEY DECIMAL(10,2) DEFAULT 0.00;
	DECLARE YEAR_SUCCESS_COUNT INT DEFAULT 0;
	DECLARE MONTH_SUCCESS_MONEY DECIMAL(10,2) DEFAULT 0.00;
	DECLARE MONTH_SUCCESS_COUNT INT DEFAULT 0;
	DECLARE WEEK_SUCCESS_MONEY DECIMAL(10,2) DEFAULT 0.00;
	DECLARE WEEK_SUCCESS_COUNT INT DEFAULT 0;
	DECLARE DAY_SUCCESS_MONEY DECIMAL(10,2) DEFAULT 0.00;
	DECLARE DAY_SUCCESS_COUNT INT DEFAULT 0;
	DECLARE DAY_REFUNDED_MONEY DECIMAL(10,2) DEFAULT 0.00;
	DECLARE DAY_REFUNDED_COUNT INT DEFAULT 0;
	DECLARE DAY_PAYMENT_FAILURE_MONEY DECIMAL(10,2) DEFAULT 0.00;
	DECLARE DAY_PAYMENT_FAILURE_COUNT INT DEFAULT 0;
	
	SELECT IFNULL(SUM(PayMoney),0.00),COUNT(*)
	INTO YEAR_SUCCESS_MONEY,YEAR_SUCCESS_COUNT
	FROM TransactionBill
	WHERE OrderStatus = 20
	AND DATE_FORMAT(CreateDateTime,'%Y') = DATE_FORMAT(NOW(),'%Y');

	SELECT IFNULL(SUM(PayMoney),0.00),COUNT(*)
	INTO MONTH_SUCCESS_MONEY,MONTH_SUCCESS_COUNT
	FROM TransactionBill
	WHERE OrderStatus = 20
	AND DATE_FORMAT(CreateDateTime,'%Y-%m') = DATE_FORMAT(NOW(),'%Y-%m');

	SELECT IFNULL(SUM(PayMoney),0.00),COUNT(*)
	INTO WEEK_SUCCESS_MONEY,WEEK_SUCCESS_COUNT
	FROM TransactionBill
	WHERE OrderStatus = 20
	AND DATE_FORMAT(CreateDateTime,'%Y-%u') = DATE_FORMAT(NOW(),'%Y-%u');

	SELECT IFNULL(SUM(PayMoney),0.00),COUNT(*)
	INTO DAY_SUCCESS_MONEY,DAY_SUCCESS_COUNT
	FROM TransactionBill
	WHERE OrderStatus = 20
	AND DATE_FORMAT(CreateDateTime,'%Y-%m-%d') = NOW();
	
	SELECT COUNT(*)
	INTO DAY_REFUNDED_COUNT
	FROM TransactionBill
	WHERE OrderStatus = 40
	AND DATE_FORMAT(CreateDateTime,'%Y-%m-%d') = NOW();

	SELECT IFNULL(SUM(RefundMoney),0.00)
	INTO DAY_REFUNDED_MONEY
	FROM OrderRefund
	WHERE RefundStatus = 1
	AND DATE_FORMAT(CreateDateTime,'%Y-%m-%d') = NOW();

	SELECT IFNULL(SUM(PayMoney),0.00),COUNT(*)
	INTO DAY_PAYMENT_FAILURE_MONEY,DAY_PAYMENT_FAILURE_COUNT
	FROM TransactionBill
	WHERE OrderStatus = 50
	AND DATE_FORMAT(CreateDateTime,'%Y-%m-%d') = NOW();


	SELECT YEAR_SUCCESS_MONEY,YEAR_SUCCESS_COUNT,
			MONTH_SUCCESS_MONEY,MONTH_SUCCESS_COUNT,
			WEEK_SUCCESS_MONEY,WEEK_SUCCESS_COUNT,
	DAY_SUCCESS_MONEY,DAY_SUCCESS_COUNT,DAY_REFUNDED_MONEY,DAY_REFUNDED_COUNT,DAY_PAYMENT_FAILURE_MONEY,DAY_PAYMENT_FAILURE_COUNT;
END