DROP PROCEDURE `V_USER_INTEGRAL_RANKING`//
CREATE DEFINER=`root`@`localhost` PROCEDURE `V_USER_INTEGRAL_RANKING`(IN USERID INT)
BEGIN 
	DECLARE KILLER_RANKING INT DEFAULT 0;
	DECLARE DETECTIVE_RANKING INT DEFAULT 0;
	DECLARE PEOPLE_RANKING INT DEFAULT 0;
	DECLARE TOTAL_RANKING INT DEFAULT 0;

	DECLARE KILLER_INTEGRAL INT DEFAULT 0;
	DECLARE DETECTIVE_INTEGRAL INT DEFAULT 0;
	DECLARE PEOPLE_INTEGRAL INT DEFAULT 0;
	DECLARE TOTAL_INTEGRAL INT DEFAULT 0;

	SELECT TABLE_B.ROWNUM,TABLE_B.INTEGRAL
	INTO KILLER_RANKING,KILLER_INTEGRAL
	FROM
	(
		SELECT T.*, @ROWNUM := @ROWNUM + 1 AS ROWNUM
		FROM (SELECT @ROWNUM := 0) R,
		(
			SELECT F1_A802,SUM(F2_A802) AS INTEGRAL 
			FROM A_802 
			WHERE F6_A802 = 1 
			GROUP BY F1_A802 
			ORDER BY INTEGRAL DESC
		) AS T
	) AS TABLE_B WHERE TABLE_B.F1_A802 = USERID;

	SELECT TABLE_B.ROWNUM,TABLE_B.INTEGRAL
	INTO DETECTIVE_RANKING,DETECTIVE_INTEGRAL
	FROM
	(
		SELECT T.*, @ROWNUM := @ROWNUM + 1 AS ROWNUM
		FROM (SELECT @ROWNUM := 0) R,
		(
			SELECT F1_A802,SUM(F2_A802) AS INTEGRAL 
			FROM A_802 
			WHERE F6_A802 = 2 
			GROUP BY F1_A802 
			ORDER BY INTEGRAL DESC
		) AS T
	) AS TABLE_B WHERE TABLE_B.F1_A802 = USERID;
	
	SELECT TABLE_B.ROWNUM,TABLE_B.INTEGRAL
	INTO PEOPLE_RANKING,PEOPLE_INTEGRAL
	FROM
	(
		SELECT T.*, @ROWNUM := @ROWNUM + 1 AS ROWNUM
		FROM (SELECT @ROWNUM := 0) R,
		(
			SELECT F1_A802,SUM(F2_A802) AS INTEGRAL 
			FROM A_802 
			WHERE F6_A802 = 3 
			GROUP BY F1_A802 
			ORDER BY INTEGRAL DESC
		) AS T
	) AS TABLE_B WHERE TABLE_B.F1_A802 = USERID;

	SELECT TABLE_B.ROWNUM,TABLE_B.INTEGRAL
	INTO TOTAL_RANKING,TOTAL_INTEGRAL
	FROM
	(
		SELECT T.*, @ROWNUM := @ROWNUM + 1 AS ROWNUM
		FROM (SELECT @ROWNUM := 0) R,
		(
			SELECT F1_A802,SUM(F2_A802) AS INTEGRAL 
			FROM A_802 
			GROUP BY F1_A802 
			ORDER BY INTEGRAL DESC
		) AS T
	) AS TABLE_B WHERE TABLE_B.F1_A802 = USERID;
	
	SELECT KILLER_RANKING,KILLER_INTEGRAL,DETECTIVE_RANKING,DETECTIVE_INTEGRAL,PEOPLE_RANKING,PEOPLE_INTEGRAL,TOTAL_RANKING,TOTAL_INTEGRAL;
	
	/** CALL V_USER_INTEGRAL_RANKING(2); */
END
