<?php echo $this->render('include/header.phtml'); ?>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<?php echo $this->render('include/css.phtml'); ?>
<?php echo $this->render('include/js.phtml'); ?>
<?php echo $this->render('include/table.phtml'); ?>
<?php echo $this->render('include/expander.phtml'); ?>
<?php echo $this->render('include/ui.phtml'); ?>
</head>
<?php echo $this->render('include/title.phtml');?>
	<div class="contentcontainer">
		<div class="contentbox">
			<table width="100%" class="table-list">
				<thead>
					<tr>
						<th style="text-align: center; width: 10px;">#</th>
						<th>功能组名称</th>
						<th></th>
						<th style="text-align: right;"><a href="/admin/group.sort" class="btn">功能组排序</a></th>
					</tr>
				</thead>
				<tbody>
					<tr class="alt">
						<form name="formNew" action="/admin/group.list" method="post" target="_self">
							<input type="hidden" name="act" value="edit">
							<input type="hidden" name="Id" value="0">
							<input type="hidden" name="rand" value="<?php echo Func::RandomKeys(8);?>" />
							<td>#</td>
							<td><input type="text" name="title" value="" style="width: 90%;"></td>
							<td style="text-align: right;">
								<input type="submit" value="新增" class="btn" style="height: 24px;">
							</td>
						</form>
						<td></td>
					</tr>
					<?php foreach ( $this->group->GetItems () as $groupKey => $groupValue ):?>
					<tr class="alt">
						<td id="GUID_<?php echo $groupValue->GetId();?>">#</td>
						<form name="formEdit<?php echo $groupValue->GetId()?>" action="/admin/group.list" method="post" target="_self">
							<input type="hidden" name="act" value="edit">
							<input type="hidden" name="rand" value="<?php echo Func::RandomKeys(8);?>" />
							<input type="hidden" name="Id" value="<?php echo $groupValue->GetId();?>">
							<td><input type="text" name="title" value="<?php echo $groupValue->GetTitle();?>" style="width: 90%;"></td>
							<td style="text-align: right;"><input type="submit" value="更新" class="btn" style="height: 24px;"></td>
						</form>
						<form name="formDelete<?php echo $groupValue->GetId();?>" action="/admin/group.list" method="post" target="_self">
							<input type="hidden" name="act" value="delete">
							<input type="hidden" name="rand" value="<?php echo Func::RandomKeys(8);?>" />
							<input type="hidden" name="Id" value="<?php echo $groupValue->GetId();?>">
							<td style="text-align: right;"><input type="submit" value="删除" class="btn" style="height: 24px;"></td>
						</form>
					</tr>
					<?php endforeach;?>
                </tbody>
			</table>
			<div style="clear: both;"></div>
		</div>
	</div>
<?php echo $this->render('include/footer.phtml'); ?>