<?php echo $this->render('include/header.phtml'); ?>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<?php echo $this->render('include/css.phtml'); ?>
<?php echo $this->render('include/js.phtml'); ?>
<?php echo $this->render('include/ui.phtml'); ?>		
</head>
<?php echo $this->render('include/title.phtml');?>
	<form action="/admin/password" target="_self" method="post" />
		<input type="hidden" name="act" value="setPassword" />
		<input type="hidden" name="rand" value="<?php echo Func::RandomKeys(8);?>" />
		<div class="contentcontainer left">
			<div class="contentbox">
				<p>
					<label for="textfield"><strong>原密码:</strong></label> <input
						type="password" name="password" class="inputbox" /><br /> <span
						class="smltxt">(请输入当前所用的密码)</span>
				</p>
				<p>
					<label for="textfield"><strong>新密码:</strong></label> <input
						type="password" name="newPassword" class="inputbox" /><br /> <span
						class="smltxt">(请输入即将使用的新密码)</span>
				</p>
				<p>
					<label for="textfield"><strong>确认新密码:</strong></label> <input
						type="password" name="retryPassword" class="inputbox" /><br /> <span
						class="smltxt">(请重新输入即将使用的新密码，以便确认)</span>
				</p>
				<input type="submit" value="提交" class="btn" />
			</div>
		</div>
	</form>
<?php echo $this->render('include/footer.phtml'); ?>